apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: external-secrets
            name: aws-credentials
            key: aws_access_key_id
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: aws-credentials
            key: aws_secret_access_key