apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    version: v1.16.1
    namespace: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    valuesInline:
      installCRDs: true
resources:
  - namespace.yaml
  - cluster-issuer.yaml
  - cloudflare-secret.yaml
